config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, sign_out_via: [:get, :post]

  namespace :api, defaults: { format: :json } do
    post 'auth/login', to: 'authentication#login'
    resources :users, only: %i[create update destroy] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
    end
   end
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]
    end
  end
    root to: 'users#index'
end

  

app/views/partials/_post.html.erb
<li>
  <h3> <%= post.title %></h3>
 <h3> <%= truncate(post.text, :length => 150) %> </h3>
 <strong>
  <h4 class="placeholder stats">
   Comments: <%= post.comments_counter %>,
   Likes: <%= post.likes_counter %> </h4>
 </strong>
  <% post.recent_five_comments.each do |comment| %>
    <h4> <%= comment.user.name%>: <%= comment.text%><p>
     <% if can? :destroy, comment %>
      <%= link_to "Delete Comment", user_post_comment_path(post.user, post, comment), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <% end %>
  <% end %>
</li>

app/views/partials/_user.html.erb
<div class='user-card'>
   <div class="image-container">
   <%= link_to user_path(user.id) do %>
   <img src=<%= user.photo %> alt="Profile picture of <%= user.name%>" />
   <% end %>
  </div>
  <div class="user-info">
    <h3><%= user.name %></h3>
    <p class="placeholder">Number of Posts: <%= user.posts_counter%> </p>
   </div>
</div>