config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, sign_out_via: [:get, :post]

  namespace :api, defaults: { format: :json } do
    post 'auth/login', to: 'authentication#login'
    resources :users, only: %i[create update destroy] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
    end
   end
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]
    end
  end
    root to: 'users#index'
end

  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, dependent: :destroy, foreign_key: :user_id
  has_many :comments, dependent: :destroy, foreign_key: :user_id
  has_many :likes, dependent: :destroy, foreign_key: :user_id

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # Compare this snippet from app\models\post.rb:
  def recent_three_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<section class='list'>
<h1> hello world </h1>
<% @users.each do |user| %>
   <%= render 'partials/user', user: user %>
<% end %>
<%= link_to 'log out', destroy_user_session_path, data: { turbo_method: :delete}%>
</section>

app/views/users/show.html.erb
<section class="list">
<%= render 'partials/user', user: @user %>
<div class='bio'>
<h3>Bio </h3>
<p><%= @user.bio %></p>
<button class='btn'><%= link_to 'Create Post', new_user_post_path(@user)%></button>
</div>
<ul class='card'>
    <% @user.recent_three_posts.each_with_index do |post, index| %>
        <p>Post #<%= index+1 %></p>
        <%= render 'partials/post', post: post %>
    <a href="/users/<%= @user.id %>/posts/<%= post.id %>"> See more</a>
    <% end %>
</ul>
<button class="btn"><%= link_to "See all posts", user_posts_path(@user.id)%></button>
</section>