config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users, sign_out_via: [:get, :post]

  namespace :api, defaults: { format: :json } do
    post 'auth/login', to: 'authentication#login'
    resources :users, only: %i[create update destroy] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
    end
   end
  end
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new, :destroy] do
      resources :comments, only: [:create, :new, :destroy]
        resources :likes, only: [:create]
    end
  end
    root to: 'users#index'
end

  

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id

  after_create :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_five_comments
    comments.includes([:user]).order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    user.increment!(:posts_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authorize_request
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :desc).includes(:comments)

    json_response(@posts)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @pagy, @posts = pagy(@user.posts.order(created_at: :desc), items: 3)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_path(@user)
        else
          flash[:error] = 'Post not created'
          render :new
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    user = User.find(post.user_id)
    user.posts_counter -= 1
    post.destroy
    user.save
    flash[:success] = 'You have deleted this post!'
    redirect_to user_posts_path(user)
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text, :likes_counter, :comments_counter)
  end
end

app/views/posts/index.html.erb
<section class='list'>
  <%= render'partials/user', user: @user %>
<button class="back"><%= link_to 'back', users_path %></button>
   <% @posts.each do |post| %>
    <ul class="post-list">
    <%= render 'partials/post', post: post %>
    </ul>
    <% end %>
  <div class='pagy'>
 <%== pagy_nav(@pagy) %>
    </div>
</section>

app/views/posts/new.html.erb
<section class='added'>
<h3>Create Post</h3>
<%= form_with model: @post, url: user_posts_path, method: :post, scope: :new_post do |form| %>
  <div class="label">
    <%= form.label :Subject %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="add">
    <%= form.label :Comment %>
    <%= form.text_area :text, class: "form-control text" %>
  </div>
    <div class='submit'>
    <%= form.submit %>
    </div>
<% end %>
</section>

app/views/posts/show.html.erb
<button class='back'><%= link_to 'Back', user_posts_path(@user.id) %></button>
<section class="posts">
  <div class="card-info">
    <div class='span'>
      <h3> <%=@post.title%> by <%= @user.name%> </h3>
      <p class="text"> Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %> </p>
    </div>
    <h4> <%= @post.text%> </h4>
  </div>

  <% if can? :destroy, @post %>
       <%= button_to 'Delete Post',
             user_post_path,
             data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
     <% end %>

  <ul class='action'>
    <%= form_with url: "/users/#{@post.user_id}/posts/#{@post.id}/likes" do |f| %>
    <button type="submit">
    <%= image_tag "https://www.facebook.com/reaction/image/1635855486666999/?size=20&scale=1", class: "group-hover:scale-125 transition ease-in duration-100"%>
    likes
    </button>
  <% end %>

  <button>
    <%= link_to new_user_post_comment_path(@user.id, @post.id) do %>
   <i data-visualcompletion="css-img" class="group-hover:scale-110 transition ease-in duration-100" style="background-image: url(&quot;https://static.xx.fbcdn.net/rsrc.php/v3/yK/r/H6IBF1RX3vl.png&quot;); background-position: 0px -213px; background-size: auto; width: 18px; height: 18px; background-repeat: no-repeat; display: inline-block;"></i>
   comments
  </button>
    <% end %>
  </ul>

    <div class="card-info">
    <% @post.comments.each do |comment| %>
      <p> <%= comment.user.name%>: <%= comment.text%><p>
    <% end %>  
  </div>
</section>